### ISSUE TITLE
pre-trained model performance

### ISSUE THREAD

**Issue by Ryan-Zirui-Wang** [xingyul/flownet3d#25]
Hi xingyul,

Thanks for the code and the pre-trained model. 
I run the `evaluation.py` over the pre-trained model you provided but I got performance output below:
```
eval mean loss: 0.404094
eval mean EPE 3D: 0.790930
eval mean ACC 3D: 0.000854
eval mean ACC 3D 2: 0.006859
```

maybe it's an untrained model? or did I do it in the wrong way?

Best,
Zirui

**Comment by xEnVrE** [comment]
Hi, @Ryan-Zirui-Wang 

I had similar issues as yours due to wrong `sm` architecture in the `Makefile` of custom tensorflow operators. As an example, consider the following

https://github.com/xingyul/flownet3d/blob/3a4b3b6377c18cc5d32c7bdf0b2a0833df809aed/tf_ops/3d_interpolation/Makefile#L12

After rebuild of operators with the correct architecture I had the right results. Hope this helps.

**Comment by Ryan-Zirui-Wang** [comment]
Hi @xEnVrE,

Many thanks for your help. Mine is `sm_61` and I did try to re-compile operators but the problem remains... so it must be something wrong at my side if the pre-trained model works on your machine.

Best,
Zirui
